name: Obfuscate_Vless

on:
    # push:
    #     paths:
    #         - 'mw_worker.js'
    workflow_dispatch:

jobs:
  obfuscate:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install -g javascript-obfuscator

      - name: Obfuscate Vless
        run: |
          if [ -f "mw_worker.js" ]; then
            javascript-obfuscator mw_worker.js --output _worker.js \
            --compact true \
            --control-flow-flattening true \
            --control-flow-flattening-threshold 1 \
            --dead-code-injection true \
            --dead-code-injection-threshold 0.4 \
            --identifier-names-generator hexadecimal \
            --rename-globals true \
            --string-array true \
            --string-array-encoding 'rc4' \
            --string-array-threshold 1 \
            --transform-object-keys true \
            --unicode-escape-sequence true
          else
            echo "Error: mw_worker.js not found!"
            exit 1
          fi

      - name: Commit changes Vless_worker
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add _worker.js
          # 仅当文件有变化时提交
          if ! git diff --cached --quiet; then
            git commit -m "Obfuscate _worker.js"
            echo "Changes committed"
          else
            echo "No changes to commit"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@v0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
